AWSTemplateFormatVersion: 2010-09-09
Description: Automatic deployment of an Airflow Managed Environment.
Parameters:
  S3BucketName:
    Type: String
    Default: <YOUR BUCKET NAME HERE>
  S3FilePrefix:
    Type: String
    Default: <YOUR AIRFLOW FILE PREFIX HERE>
  S3Project:
    Type: String
    Default: <YOUR AIRFLOW PROJECT NAME HERE>
  DAGLOCATION:
    Type: String
    Default: DAGs
  SCRIPTLOCATION:
    Type: String
    Default: scripts

Resources:
  GenericManagedAirflow:
    Type: AWS::MWAA::Environment
    Properties:
      AirflowVersion: "1.10.12"
      DagS3Path: !Sub "s3://${S3BucketName}/${S3FilePrefix}/${DAGLOCATION}/"
      ExecutionRoleArn: !GetAtt GenericMWAARole.Arn
      KmsKey: String
      MaxWorkers: 10
      NetworkConfiguration:
        SecurityGroupIds:
          - <add Security group for VPC>
        SubnetIds:
          - <add SubnetIDs for VPC>
      PluginsS3Path: !Sub "s3://${S3BucketName}/${S3FilePrefix}/${SCRIPTLOCATION}/plugins.zip"
      RequirementsS3ObjectVersion: String
      RequirementsS3Path: !Sub "s3://${S3BucketName}/${S3FilePrefix}/${SCRIPTLOCATION}/requirements.txt"
      SourceBucketArn: <Sub in ARN for S3 Bucket Here>
      ServiceRole: !GetAtt GenericMWAARole.Arn
      Tags:
        - Key: "MyTag"
          Value: "AK_Template"
      WebserverAccessMode: String
      WebserverUrl: String
      WeeklyMaintenanceWindowStart: "TUE:03:30"

  GenericMWAARole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Generic-MWAA-Role
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: MWAAAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - "airflow:PublishMetrics"
                Effect: Allow
                Resource: "arn:aws:airflow:{{region}}:{{accountId}}:environment/{{envName}}"
              - Action:
                  - "sqs:ChangeMessageVisibility"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                  - "sqs:GetQueueUrl"
                  - "sqs:ReceiveMessage"
                  - "sqs:SendMessage"
                  - "kms:Decrypt"
                  - "kms:DescribeKey"
                  - "kms:GenerateDataKey*"
                  - "kms:Encrypt"
                  Effect: Allow
                  Resource: "arn:aws:sqs:{{region}}:*:airflow-celery-*"
              - Action:
                  - "kms:Decrypt"
                  - "kms:DescribeKey"
                  - "kms:GenerateDataKey*"
                  - "kms:Encrypt"
                  Effect: Allow
                  Resource: "arn:aws:kms:*:{{accountId}}:key/*"
                  "Condition": {
                    "StringLike": {
                      "kms:ViaService": [
                          "sqs.{{region}}.amazonaws.com",
                          "s3.{{region}}.amazonaws.com"
                      ]
                    }
                  }
              - Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - "s3:List*"
                  - "s3:GetObjectVersion"
                  - "logs:*"
                  - "cloudwatch:PutMetricData"
                  Effect: Allow
                  Resource: '*' # Don't keep this as * permissions. Update to the specific bucket you're using.
      Tags:
        - Key: "MyTag"
          Value: "AK_Template"
